workflowSampleServices:
  docProcessMcpServer:
    name: doc-process-mcp-server
    image: docker.io/library/doc-process-mcp-server:latest
    imagePullSecret: regcred
    replicaCount: 1

  loanComplianceService:
    name: loan-compliance-service
    image: docker.io/library/loan-compliance-service:latest
    imagePullSecret: regcred
    replicaCount: 1

  loanProcessingAgent:
    name: loan-processing-agent
    image: docker.io/library/loan-processing-agent:latest
    imagePullSecret: regcred
    replicaCount: 1

  notificationService:
    name: notification-service
    image: docker.io/library/notification-service:latest
    imagePullSecret: regcred
    replicaCount: 1

  ocrService:
    name: ocr-service
    image: docker.io/library/ocr-microservice:latest
    imagePullSecret: regcred
    replicaCount: 1
